### ISSUE TITLE
Add a notebook that replicates the setup and results of the benchmark 7 of Jean-Francois Aubry et al paper

### ISSUE THREAD

**Issue by d-lucena** [agencyenterprise/neurotechdevkit#89]
## Describe the new feature or enhancement

A notebook that describes how to replicate the results as those in the benchmark 8 using NDK

## Describe your proposed implementation

Show how to setup the scenario, setup material properties, transducer position and properties, and run the simulation that replicates the results in [Jean-Francois Aubry, et al.](https://doi.org/10.1121/10.0013426).
The results from NDK and from the paper are then presented together to show they match.

**Comment by charlesincharge** [comment]
Because of how long benchmark 4 already takes to run (and benchmark 8 is longer), we are just going to run this benchmark in 2D.

Another option would be to run this with smaller slices (i.e., more local around the transducer+target region, or the comparison slice).

**Comment by charlesincharge** [comment]
Based on offline discussion, we are going to change this to benchmark 7, which fits on a GPU at `PPW=6` `PPW=24`
